### ISSUE TITLE
`latest` throws 404 for a few minutes afer a new release

### ISSUE THREAD

**Issue by psteinroe** [supabase/setup-cli#115]
# Bug report

## Describe the bug

When using `latest`, a 404 error is thrown.

## To Reproduce

use `version: latest`

## Expected behavior

![Screenshot 2023-01-05 at 10 31 28](https://user-images.githubusercontent.com/19429600/210747425-a6701ee1-de68-4a19-b9ba-e0edd175d811.png)

**Comment by sweatybridge** [comment]
Just to confirm, is this on Ubuntu runner? Could you also run again with debug logging enabled?

Our ci test on Ubuntu seems successful so far https://github.com/supabase/setup-cli/actions/runs/3845510512/jobs/6551483706

**Comment by sweatybridge** [comment]
I think what could have happened is after a new cli release, the GitHub release page is created first before binaries are built and uploaded. This means there is a 5 mins window after each release where the `latest` version will return 404.

Perhaps we can make a prerelease first as a placeholder then finish the release on post run. I will move this issue to cli repo and prioritise accordingly.

**Comment by ruggi99** [comment]
Maybe make a new draft release with semantic and make it public once the Go Releaser has finished using GitHub API

**Comment by sweatybridge** [comment]
CLI release workflow has been updated to address this issue.
