### ISSUE TITLE
500 error while pulling images on v1.1.5

### ISSUE THREAD

**Issue by maxkostow** [supabase/setup-cli#131]
# Bug report

## Describe the bug

There is a 500 error when pulling images which causes the action to fail

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use the `setup-cli@v1` action with `version: 1.30.0`
2. Run `supabase start`
3. See the error

```
Run supabase start
Pulling images... (1/13)
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
Retrying after 4s: ghcr.io/supabase/postgres:14.1.0.[8]
Error response from daemon: unauthorized
Retrying after 8s: ghcr.io/supabase/postgres:14.1.0.89
Error: Error response from daemon: Head "https://ghcr.io/v2/supabase/postgres/manifests/14.1.0.89": received unexpected HTTP status: 500 Internal Server Error
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```

## Expected behavior

CLI downloads images normally

## Additional context

Using `setup-cli@1.1.4` seems to work as expected

**Comment by maxkostow** [comment]
Maybe related to https://www.githubstatus.com/incidents/zf2tk6x40gmh?

**Comment by gschechter** [comment]
> Maybe related to https://www.githubstatus.com/incidents/zf2tk6x40gmh?

Started chasing this down, and with that resolved being `Posted 3 minutes ago. Jan 30, 2023 - 22:23 UTC` it seems to have indeed been that.
