### ISSUE TITLE
CI Migrations & vector extension

### ISSUE THREAD

**Issue by mosnicholas** [supabase/setup-cli#135]
# Describe the bug
Getting an error trying to run migrations the recommended way through Github actions. I recently enabled the vector extension, and seeing the migration fail.

```
Applying migration 20230209001317_embeddings.sql...
Error: ERROR: extension "vector" is not available (SQLSTATE 0A000)
At statement 0: create extension if not exists "vector" with schema "public" version '0.4.0'
```

## To Reproduce
1. Follow steps [here](https://supabase.com/docs/guides/cli/managing-environments) to setup CI based migrations.
2. Enable the vector extension (or add to your initial migration file the line: `create extension if not exists "vector" with schema "public" version '0.4.0';`).
3. Push to github

## Expected behavior
It should work, instead the GitHub action fails with the error message posted above

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by sweatybridge** [comment]
Hi @mosnicholas, the default CLI version installed by this action does not have the latest features. Could you try specifying the `latest` version instead?

```yaml
- uses: supabase/setup-cli@v1
  with:
    version: latest
```
