### ISSUE TITLE
 extension "pg_tle" is not available

### ISSUE THREAD

**Issue by sagi-gamago** [supabase/setup-cli#177]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I run CI with git actions and trying to use PG_TLE in my SQL scripts

## To Reproduce

Have this action in the git workflow:
```
name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - name: Start Supabase local development setup
        run: |
          supabase db start
          supabase db lint
          supabase test db

      - name: Verify generated types are up-to-date
        run: |
          supabase gen types typescript --local > types.ts
          if [ "$(git diff --ignore-space-at-eol types.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
```

and have the following script in the migration file:
```SQL
CREATE EXTENSION IF NOT EXISTS pg_tle;
```

## Expected behavior

I expected it to run successfully in the git actions

## Screenshots

![image](https://github.com/supabase/setup-cli/assets/134994751/39c7937c-c22d-45e0-bfa8-f0fb0b0442ce)

## System information

- Git actions

## Additional context

I'm trying to have a CI process that have "usebasejump/supabase-test-helpers"
In order to have it them I need pg_tle.

**Comment by sweatybridge** [comment]
pg_tle support is only added recently so you need to pin the setup cli to the `latest` version. 

```yaml
- uses: supabase/setup-cli@v1
  with:
    version: latest
```
