### ISSUE TITLE
Error: Unable to resolve action. Repository not found: supabase/setup-cli

### ISSUE THREAD

**Issue by MaciekBaron** [supabase/setup-cli#199]
As of today the actions started failing with:

```
Error: Unable to resolve action. Repository not found: supabase/setup-cli
```

[Github Status](https://www.githubstatus.com/) not reporting any issues with actions

**Comment by sweatybridge** [comment]
Sorry about that. We renamed the repo today and tested [here](https://github.com/supabase/supabase-action-example/actions/runs/5613678777/job/15424194065). But may be it was pulling from a cached repo.

I've renamed the repo back to setup-cli. Let me know if it resolves the issue.

**Comment by MaciekBaron** [comment]
Thanks for your quick response! Will run some tests now.

**Comment by MaciekBaron** [comment]
Can confirm it works again! Thank you for your help.
